stages:
  - build
  - package

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

#{build stage to compile the back}
build:
  image: node:20-slim
  stage: build
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

#{package stage to build the docker image}
package:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: package
  before_script:
    - mkdir -p /kaniko/.docker
    - cp $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
    - ls build/
    - cp -r ./build/ docker/
  script: 
     - /kaniko/executor 
        --context "${CI_PROJECT_DIR}/docker" 
        --dockerfile ${CI_PROJECT_DIR}/docker/Dockerfile 
        --destination "s0nren/movierizer-front:${FRONT_VERSION}" 
