FROM node:20-alpine AS build

COPY package*.json ./
COPY . . 

RUN npm install
RUN npm run build

FROM nginx:alpine AS run

WORKDIR /app

COPY --from=build ./build/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]