services:
  front:
    build: 
      context: '../'
      dockerfile: 'docker/Dockerfile.dev'
    image: movierizer_front_dev
    container_name: movierizer_front_dev
    restart: always
    env_file:
      - ../.env
    ports:
      - "8080:3000"
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    driver: bridge