FROM node:20-alpine AS build

WORKDIR usr/app
COPY package*.json ./
COPY . .

RUN npm install
RUN npm run build

FROM nginx:alpine AS run

WORKDIR /app

COPY --from=build ./usr/app/build/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

CMD ["/entrypoint.sh"]